language: php
php:
- 5.6
- hhvm
before_script:
- composer self-update
- composer install --prefer-source --no-interaction --dev
script: phpunit
env:
  global:
  - secure: r1LZu++7H+ymRU9MajeGLN31fd17gF4Eg//A5byGZWmi/50rWJa3TLFeZ+1sjZPKz06Ld+1cPCTJgaOKvu69YdeaxLQo5TlpeLEJSQun3UwQArzUf8EzAqjsM8hO4UGAULAeKOmI1nFQS1oi5hQK52mhxsmAnOc2IX1wW8GuqSpp37cQyN11c8uY96RwWk0RI5mXxv5kXxvFHOAF4Fmd0nQdtT+tbj5+3EVqEojUPwoP3RweIUOIYWy2tswWAMgzSkwsiYp8MiCim3FuuVxgLr5djGn0/ugcoUCbok9Dj31elNDFTJ5TORFdrgNSKFWw0EHFwe4D0JYHrd+edDp7BTvF5Azi1LrpaAiZETPhzFK9UtuT+fERR6QxnINyR1Q76OzdoaX088pWmKoVZH4kUTUvNAHe86dvQ+Wpex8WiLnFe3EVMWQLqYLoKP0+upgTLPEQ8t/Vyg0i362ZeZlAGrMNBhfZZKCj9N5xOYzpNvVlz1zfc3W2ZZ0oQPskp7XY7b4mN94evbRVLxr8fgSQttRO8Wp1f599VFHDVp8nzYp2zvB6fzsr6BZ33Qig47HheF+5LMiZXYkCkyU8db3v6t9Tqx2A37lxdKP7wAyPzYMHX4O2zOGcLH1veVZZjHJeoJ9dpec2BvEARkEhdQ0SkvbkfqYxXSng5eYGol3v2n8=
  - secure: auGHs960hggJpXTfftRPMlrilvyhpOFcw6efVeRJX8FIiWNKsXl/fW2XlQKj/Q6blO+epQr7Fy4asJlBGhcM2SHV2lZUJ43GuwxfrkLKRgjKVn0PlpXSU4GrQ0ZnPsu3T2KQbjSkhf4m5zWHFLsacpW0sEYwYgrZBezbBOIpP5TFxd/wB2S/EeTNZGAHwq8sTLTpI9b8Yh6hTs1PTGnS+SOg3jO3VZ0eVy1ffsCpKiBeS2IbJN4XOX9oPwnaQn/Oq8SsKpTR5Nhe6v1h1wjvfLT1b27ouV5jhENJ4qKRVk2qV0p1hl6W3r7EcAczNF91LXVoqptnwP1BpY4IDX3EvpJB0SArwvaOmSfICJ1X9hzPpb94TSI45WGAufrPg2UtZPBAcHKRB5g0ASTlqDlHiEmlMheVn9+2mM2NREnru53zmb38XNYf6hivTevYbHKWxOHes1NU1YBLjEp0BhastDK5ubx1uO+yPUbiTerJkwsGTR+QgjIbD5dTM4PZ/PrGMKwzKQYFVTwZtC7PPKIh281qLI9B/DU71qRdwRucn7zhT85wX03tKPaclyiwLzsXrW9g4ctWD8nC6SfH6pF6mJgWvi/t0UJs8uoe5jreJH9hcVmyoGRllYuE5LmHCukxvsRCqgoyFy/Ibw77+PdE2WQufpJgLrNjH3EU4oG+y2U=
